# -*- coding: utf-8 -*-

TRUE = 'TRUE'
FALSE = 'FALSE'

STD_INPUT = 'STANDARD_INPUT'
NOTICE = 'NOTICE'
QUESTION = 'QUESTION'
NORMAL = 'NORMAL'

JUDGING = 'JUDGING'
SOLVED = 'SOLVED'
WRONG_ANSWER = 'WRONG_ANSWER'
COMPILE_ERROR = 'COMPILE_ERROR'
SERVER_ERROR = 'SERVER_ERROR'
RUNTIME_ERROR = 'RUNTIME_ERROR'
SOLUTION = 'SOLUTION'
